{{- if and .Values.concourse.web.prometheus.enabled .Values.web.enabled}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "concourse.web.fullname" . }}-prometheus
  labels:
    app: {{ template "concourse.web.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- range $key, $value := .Values.web.service.prometheus.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.concourse.web.prometheus.bindPort | quote }}
    {{- range $key, $value := .Values.web.service.prometheus.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: {{ .Values.web.service.prometheus.type }}
  {{- if .Values.web.service.prometheus.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- range .Values.web.service.prometheus.loadBalancerSourceRanges }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{- if and (eq "ClusterIP" .Values.web.service.prometheus.type) .Values.web.service.prometheus.clusterIP }}
  clusterIP: {{ .Values.web.service.prometheus.clusterIP }}
  {{- end }}
  {{- if and (eq "LoadBalancer" .Values.web.service.prometheus.type) .Values.web.service.prometheus.loadBalancerIP }}
  loadBalancerIP: {{ .Values.web.service.prometheus.loadBalancerIP }}
  {{- end }}
  ports:
    - name: prometheus
      port: {{ .Values.concourse.web.prometheus.bindPort }}
      targetPort: prometheus
      {{- if and (eq "NodePort" .Values.web.service.prometheus.type) .Values.web.service.prometheus.NodePort }}
      nodePort: {{ .Values.web.service.prometheus.NodePort}}
      {{- end }}
  selector:
    app: {{ template "concourse.web.fullname" . }}
{{- end }}
